spring.application.name=keystone-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/keystone
spring.datasource.username=postgres
spring.datasource.password=akshadakurhade

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=MySecretKeyForKeystoneProject123456789
jwt.expiration=86400000
server.port=8082